In [8]:
import sys
import os
PROJECT_ROOT = os.path.abspath("..")
sys.path.append(PROJECT_ROOT)
from src.database.mysql_client import MySQLDatabase
import pandas as pd
import numpy as np

In [11]:
db = MySQLDatabase("financialmarkets")

In [12]:
query = """   
    SELECT * 
    FROM companies;
"""
df = db.execute_query(query)
df.shape

✅ Conexión exitosa

(37332, 10)

In [13]:
df.to_excel("../data/raw/companies.xlsx", index=False)

In [17]:
df = pd.read_excel("../data/raw/companies.xlsx")

# formatos
df['company_id'] = df['company_id'].astype('int')
df['market_id'] = df['market_id'].astype('int')
df['symbol'] = df['symbol'].astype('str')
df['name'] = df['name'].astype('str')
df['sector_name'] = df['sector_name'].astype('str')
df['sub_industry'] = df['sub_industry'].astype('str')
df['date_added'] = pd.to_datetime(df['date_added'], errors="coerce")
df['headquarters'] = df['headquarters'].astype('str')
df['cik'] = df['cik'].astype('str')
df["founded"] = pd.to_numeric(df["founded"],errors="coerce").astype("int")
df.head()

,company_id,market_id,symbol,name,sector_name,sub_industry,date_added,headquarters,cik,founded
0,1,1,AACB,Artius II Acquisition Inc. - Class A Ordinary ...,SD,SD,NaT,SD,SD,9999
1,2,1,AACBR,Artius II Acquisition Inc. - Rights,SD,SD,NaT,SD,SD,9999
2,3,1,AACBU,Artius II Acquisition Inc. - Units,SD,SD,NaT,SD,SD,9999
3,4,1,AACG,ATA Creativity Global - American Depositary Sh...,SD,SD,NaT,SD,SD,9999
4,5,1,AACI,Armada Acquisition Corp. II - Class A Ordinary...,SD,SD,NaT,SD,SD,9999

In [14]:
query = """   
    SELECT * 
    FROM markets;
"""
df = db.execute_query(query)
df.shape

(6, 4)

In [15]:
df.to_excel("../data/raw/markets.xlsx", index=False)

In [18]:
df = pd.read_excel("../data/raw/markets.xlsx")
df.head()

   market_id market_name country currency
0          1      NASDAQ     USA      USD
1          2     S&P 500     USA      USD
2          3      IPC MX      MX     Peso
3          4         DAX  GERMAN      DEM
4          5     FTSE100     UKX      GBP

In [19]:
df['market_id'] = df['market_id'].astype('int')
df['market_name'] = df['market_name'].astype('str')
df['country'] = df['country'].astype('str')
df['currency'] = df['currency'].astype('str')
df.head()

   market_id market_name country currency
0          1      NASDAQ     USA      USD
1          2     S&P 500     USA      USD
2          3      IPC MX      MX     Peso
3          4         DAX  GERMAN      DEM
4          5     FTSE100     UKX      GBP